# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_patient_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='time_iso',
            field=models.CharField(default='2018-01-01T01:00:00', max_length=19),
        ),
    ]
