# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_reading_time_iso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='timestamp',
            new_name='time_epoch',
        ),
    ]
