# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_auto_20180129_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reading',
            old_name='value',
            new_name='value_hr',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='quality',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='type',
        ),
    ]
