# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0006_auto_20180129_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='value_activity',
            field=models.FloatField(default=0.78),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_bperf',
            field=models.FloatField(default=0.35),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_hrv',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_rr',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_spo2',
            field=models.IntegerField(default=99),
        ),
        migrations.AlterField(
            model_name='reading',
            name='value_hr',
            field=models.IntegerField(default=80),
        ),
    ]
