# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0007_auto_20180129_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='limits_bperf_max',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_bperf_min',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_hr_max',
            field=models.FloatField(default=110),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_hr_min',
            field=models.FloatField(default=70),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_rr_max',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_rr_min',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_spo2_max',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='limits_spo2_min',
            field=models.FloatField(default=94),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_update',
            field=models.CharField(default='2018-01-20T01:00:00', max_length=19),
        ),
    ]
