# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models
import plot.models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0009_patient_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=18)),
                ('file_name', models.CharField(max_length=255)),
                ('attachment', models.FileField(upload_to=plot.models.upload_to)),
                ('user_id', models.IntegerField(default=-1)),
            ],
            options={
                'ordering': ['-file_name'],
            },
        ),
    ]
