# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-03 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0011_auto_20180203_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='value_steps',
            field=models.IntegerField(default=0),
        ),
    ]
