# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-08 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0012_reading_value_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='value_duration',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_fev1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_fev1_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_fvc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_fvc_predicted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_pef',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_ratio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reading',
            name='value_ratio_predicted',
            field=models.IntegerField(default=0),
        ),
    ]
