# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-16 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0014_auto_20180206_1346'),
        ('plot', '0013_auto_20180208_0554'),
    ]

    operations = [
    ]
