# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0018_auto_20180301_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apilog',
            old_name='datetime',
            new_name='date',
        ),
    ]
